version: "3.7"

services:
  identity:
    build: .
    depends_on:
      - postgres-migrate
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - PORT=8080
      - TOKEN_SECRET=${TOKEN_SECRET}
    image: identity
    ports:
      - 8080:8080

  postgres:
    environment:
      - POSTGRES_DB=identity
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
    image: postgres:12.0
    restart: always

  postgres-migrate:
    command: -database postgres://$DATABASE_USERNAME:$DATABASE_PASSWORD@postgres:5432/identity?sslmode=disable -path=/migrations/ up
    depends_on:
      - postgres
    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
    image: migrate/migrate
    restart: on-failure
    volumes:
      - ./migrate/sql:/migrations
