version: "3.7"

services:
  identity:
    build: .
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - PORT=8080
      - TOKEN_SECRET=${TOKEN_SECRET}
    image: identity
    ports:
      - 8080:8080

  postgres:
    environment:
      - POSTGRES_DB=identity
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
    image: postgres:12.0
    restart: always
