name: Build

on: [push]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run unit tests
        run: go test $(go list ./... | grep -v /test/)
      - name: Start docker services
        run: docker-compose up -d
      - name: Run acceptance tests
        run: go test ./test/acceptance/...
