name: Build

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run unit tests
        run: go test $(go list ./... | grep -v /test/)
      - name: Print docker configuration
        run: docker-compose config
      - name: Start docker services
        run: docker-compose up -d
      - name: Run acceptance tests
        run: go test ./test/acceptance/...
      - if: failure()
        name: Print docker logs
        run: docker-compose logs
